version: '3'

services:
  postgres:
    image: 'bitnami/postgresql'
    restart: 'always'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_DATABASE: 'crud-koa'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
